log:
  filePath: "/var/log/traefik/traefik.log"
  level: "DEBUG"

accesslog:
  filePath: "/var/log/traefik/access.log"

  ################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: false
  # debug: true

################################################################
# Docker configuration backend
################################################################
providers:
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true
  docker:
    watch: true
    exposedByDefault: false

################################################################
# Traefik Logging
################################################################
#log:
#  level: DEBUG

################################################################
# Entrypoint
################################################################
#entryPoints:
#  web:
#    address: ":80"
#  websecure:
#    address: ":443"
#    http:
#      tls: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls: true
